global_mem_key_last_room_state_refresh = 'sr'
global_mem_key_room_mining_paths = 'mp'
global_mem_key_room_data = 'rd'
meta_segment_key_stored_room_data_segment_mapping = 'rs'
global_mem_key_segments_last_updated = 'su'
global_mem_key_pause_rcl8_upgrading = 'pause_upgrading'
