base_no_role = ["No role", "!!!"]

default_gather_moving_to_storage = ["G. F. S."]
default_gather_moving_between_rooms = ["G. F. BR."]
default_gather_storage_withdraw_ok = ["G. S."]
default_gather_no_sources = ["D!", "G.", "No", "S."]
default_gather_flag_no_sources = ["D! G F No S."]
default_gather_moving_to_energy = ["G. Find. E."]
default_gather_unknown_result_pickup = ["???"]
default_gather_energy_pickup_ok = ["G. E."]
default_gather_moving_to_container = ["G. Find. C."]
default_gather_container_withdraw_ok = ["G. C."]
default_gather_unknown_result_withdraw = ["G. C. ???!"]
default_gather_moving_to_source = ["G. F. S."]
default_gather_source_harvest_ok = ["G. S."]
default_gather_source_harvest_ner = ["G. W."]
default_gather_unknown_result_harvest = ["G. ???"]

upgrading_controller_not_owned = ["U. D!!"]
upgrading_ok = ["U."]
upgrading_moving_to_controller = ["U."]
upgrading_unknown_result = ["U. ???"]

tower_fill_moving_to_tower = ["T. Find."]
tower_fill_ok = ["TF."]
tower_fill_unknown_result = ["TF. ???"]

spawn_fill_moving_to_target = ["H. Find."]
spawn_fill_ok = ["H. Fill."]
spawn_fill_unknown_result = ["H. ???"]

building_repair_target = ["R. {}."]
building_build_target = ["B. {}."]

dedi_miner_moving = ["HB. F. S."]
dedi_miner_ok = ["HB."]
dedi_miner_ner = ["HB. WW."]
dedi_miner_unknown_result = ["HB. ???"]

local_hauler_no_source = ["H. N. S."]
local_hauler_no_miner = ["H. N. M."]
local_hauler_moving_to_miner = ["H. Move."]
local_hauler_waiting = ["H. WW."]
local_hauler_pickup_ok = ["H. Collect!"]
local_hauler_pickup_unknown_result = ["H. ???"]
local_hauler_no_storage = ["H. N. S!!!"]
local_hauler_moving_to_storage = ["H. Haul."]
local_hauler_transfer_ok = ["H. Store."]
local_hauler_storage_full = ["H. Full!!"]
local_hauler_transfer_unknown_result = ["H. ???"]

remote_miner_no_flag = ["RM. N. F."]
remote_miner_moving = ["RM. Moving."]
remote_miner_flag_no_source = ["RM. N. S!"]
remote_miner_ok = ["RM. Mining."]
remote_miner_ner = ["RM. WW."]
remote_miner_unknown_result = ["RM. ???"]

remote_hauler_no_source = ["RH. N. S."]
remote_hauler_source_no_miner = ["RH. N. M."]
remote_hauler_moving_to_miner = ["RH. Move."]
remote_hauler_ner = ["RH. WW."]
remote_hauler_pickup_ok = ["RH. Collect!"]
remote_hauler_pickup_unknown_result = ["RH. ???"]
remote_hauler_no_home_storage = ["RH. N. S!!!"]
remote_hauler_moving_to_storage = ["RH. Haul."]
remote_hauler_transfer_ok = ["RH. Store."]
remote_hauler_storage_full = ["RH. Full!!"]
remote_hauler_transfer_unknown_result = ["RH. ???"]

remote_reserve_moving = ["R.R. F. C."]
remote_reserve_reserving = ["R.R. C. C."]
